[install]
# disable isolated deps because of Expo & monorepo issues
# https://docs.expo.dev/guides/monorepos/#package-managers-with-isolated-dependencies
linker = "hoisted"
[test]
preload = ["./apps/api/tests/database-setup.ts"]
