services:
  database:
    image: postgis/postgis
    build:
      context: https://github.com/postgis/docker-postgis.git#master:18-3.6
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cruxi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cruxi"]
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"